name: build

on:
  push:
    branches: [main]
    paths-ignore:
      - "**/*.gitattributes"
      - "**/*.gitignore"
      - "**/*.md"
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  DOTNET_GENERATE_ASPNET_CERTIFICATE: false
  DOTNET_MULTILEVEL_LOOKUP: 0
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: 1
  FORCE_COLOR: 1
  NUGET_XMLDOC_MODE: skip
  TERM: xterm

jobs:
  publish-aot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4

      - name: Install .NET Workloads
        run: dotnet workload restore

      - name: Publish AOT
        shell: pwsh
        run: |
          .\build\publish-aot.ps1 -RuntimeIdentifier linux-amd64

      - name: Publish AOT Build
        uses: actions/upload-artifact@v4
        with:
          name: publish-aot-amd64
          path: ./artifacts/publish/

      - name: Get Linked Libs
        run: |
          ldd ./artifacts/publish/Console/release_linux-x64/Console
          ldd ./artifacts/publish/WebApi/release_linux-x64/WebApi
          ldd ./artifacts/publish/WebApiAot/release_linux-x64/WebApiAot
